name = "Re Robust"
license = "MIT"
licenselink = "https://github.com/ress997/hugo-rerobust/blob/master/LICENSE.md"
description = "Grid based theme for Hugo."
homepage = "https://github.com/ress997/hugo-rerobust"
tags = ["blog"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]
min_version = 0.42

[author]
name = "Ress"
homepage = "https://x39.dev"
